/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtPasswordResetRouteImport } from './routes/ext/password.reset'
import { Route as ExtEmailValidateRouteImport } from './routes/ext/email.validate'
import { Route as ExtAccountCreateRouteImport } from './routes/ext/account.create'
import { ServerRoute as ApiHealthcheckServerRouteImport } from './routes/api/healthcheck'

const rootServerRouteImport = createServerRootRoute()

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtPasswordResetRoute = ExtPasswordResetRouteImport.update({
  id: '/ext/password/reset',
  path: '/ext/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtEmailValidateRoute = ExtEmailValidateRouteImport.update({
  id: '/ext/email/validate',
  path: '/ext/email/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtAccountCreateRoute = ExtAccountCreateRouteImport.update({
  id: '/ext/account/create',
  path: '/ext/account/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthcheckServerRoute = ApiHealthcheckServerRouteImport.update({
  id: '/api/healthcheck',
  path: '/api/healthcheck',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ext/account/create': typeof ExtAccountCreateRoute
  '/ext/email/validate': typeof ExtEmailValidateRoute
  '/ext/password/reset': typeof ExtPasswordResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ext/account/create': typeof ExtAccountCreateRoute
  '/ext/email/validate': typeof ExtEmailValidateRoute
  '/ext/password/reset': typeof ExtPasswordResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ext/account/create': typeof ExtAccountCreateRoute
  '/ext/email/validate': typeof ExtEmailValidateRoute
  '/ext/password/reset': typeof ExtPasswordResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ext/account/create'
    | '/ext/email/validate'
    | '/ext/password/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ext/account/create'
    | '/ext/email/validate'
    | '/ext/password/reset'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ext/account/create'
    | '/ext/email/validate'
    | '/ext/password/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ExtAccountCreateRoute: typeof ExtAccountCreateRoute
  ExtEmailValidateRoute: typeof ExtEmailValidateRoute
  ExtPasswordResetRoute: typeof ExtPasswordResetRoute
}
export interface FileServerRoutesByFullPath {
  '/api/healthcheck': typeof ApiHealthcheckServerRoute
}
export interface FileServerRoutesByTo {
  '/api/healthcheck': typeof ApiHealthcheckServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/healthcheck': typeof ApiHealthcheckServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/healthcheck'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/healthcheck'
  id: '__root__' | '/api/healthcheck'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiHealthcheckServerRoute: typeof ApiHealthcheckServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/password/reset': {
      id: '/ext/password/reset'
      path: '/ext/password/reset'
      fullPath: '/ext/password/reset'
      preLoaderRoute: typeof ExtPasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/email/validate': {
      id: '/ext/email/validate'
      path: '/ext/email/validate'
      fullPath: '/ext/email/validate'
      preLoaderRoute: typeof ExtEmailValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/account/create': {
      id: '/ext/account/create'
      path: '/ext/account/create'
      fullPath: '/ext/account/create'
      preLoaderRoute: typeof ExtAccountCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/healthcheck': {
      id: '/api/healthcheck'
      path: '/api/healthcheck'
      fullPath: '/api/healthcheck'
      preLoaderRoute: typeof ApiHealthcheckServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ExtAccountCreateRoute: ExtAccountCreateRoute,
  ExtEmailValidateRoute: ExtEmailValidateRoute,
  ExtPasswordResetRoute: ExtPasswordResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHealthcheckServerRoute: ApiHealthcheckServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
