/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExtPasswordUpdateRouteImport } from './routes/ext/password.update'
import { Route as ExtEmailValidateRouteImport } from './routes/ext/email.validate'
import { Route as ExtAccountCreateRouteImport } from './routes/ext/account.create'

const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtPasswordUpdateRoute = ExtPasswordUpdateRouteImport.update({
  id: '/ext/password/update',
  path: '/ext/password/update',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtEmailValidateRoute = ExtEmailValidateRouteImport.update({
  id: '/ext/email/validate',
  path: '/ext/email/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtAccountCreateRoute = ExtAccountCreateRouteImport.update({
  id: '/ext/account/create',
  path: '/ext/account/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ext/account/create': typeof ExtAccountCreateRoute
  '/ext/email/validate': typeof ExtEmailValidateRoute
  '/ext/password/update': typeof ExtPasswordUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ext/account/create': typeof ExtAccountCreateRoute
  '/ext/email/validate': typeof ExtEmailValidateRoute
  '/ext/password/update': typeof ExtPasswordUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ext/account/create': typeof ExtAccountCreateRoute
  '/ext/email/validate': typeof ExtEmailValidateRoute
  '/ext/password/update': typeof ExtPasswordUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ext/account/create'
    | '/ext/email/validate'
    | '/ext/password/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ext/account/create'
    | '/ext/email/validate'
    | '/ext/password/update'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ext/account/create'
    | '/ext/email/validate'
    | '/ext/password/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ExtAccountCreateRoute: typeof ExtAccountCreateRoute
  ExtEmailValidateRoute: typeof ExtEmailValidateRoute
  ExtPasswordUpdateRoute: typeof ExtPasswordUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/password/update': {
      id: '/ext/password/update'
      path: '/ext/password/update'
      fullPath: '/ext/password/update'
      preLoaderRoute: typeof ExtPasswordUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/email/validate': {
      id: '/ext/email/validate'
      path: '/ext/email/validate'
      fullPath: '/ext/email/validate'
      preLoaderRoute: typeof ExtEmailValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ext/account/create': {
      id: '/ext/account/create'
      path: '/ext/account/create'
      fullPath: '/ext/account/create'
      preLoaderRoute: typeof ExtAccountCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ExtAccountCreateRoute: ExtAccountCreateRoute,
  ExtEmailValidateRoute: ExtEmailValidateRoute,
  ExtPasswordUpdateRoute: ExtPasswordUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
